### ISSUE TITLE
Error Py_NoneStruct

### ISSUE THREAD

**Issue by turalyf** [rouze-d/btc-puzzle#1]
![image](https://github.com/user-attachments/assets/b199eac2-3d3f-472c-b138-72ffb8b32276)

Hi. I haven't found a solution anywhere. What is the problem?

**Comment by rouze-d** [comment]
run on termux..
~$ pkg install cmake pkg-config libsecp256k1
~$ pip install setuptools
~$ pip install bit --upgrade
~$ pip install coincurve==19.0.0

(make sure coincurve is using version 19.0.0)
now run python puzzle.py

<img src="https://github.com/user-attachments/assets/07db9e95-433d-47ef-9d8a-a855545a2a9c" width="350" height="700"/>
<img src="https://github.com/user-attachments/assets/ef300b23-fbd9-4b4b-ac1b-f22d128edc22" width="350" height="700"/>

**Comment by turalyf** [comment]
Thank you very much!
They helped a lot.
Everything worked out.

I wish you and your project prosperity, move on, good luck with your life.
