### ISSUE TITLE
Range

### ISSUE THREAD

**Issue by turalyf** [rouze-d/btc-puzzle#2]
Is there a way to improve the code?
For example, you can add more for the selected range

**low = 0x100000000000000000
high = 0x1fffffffffffffffff**

If possible, please improve the project.

I am very sure that, thanks to your code, I or another person will find a bitcoin puzzle 😀

**Comment by emezelenme** [comment]
and how to make the general scan show without a public address, wif and hex, only show the total number of scans?

**Comment by rouze-d** [comment]
> and how to make the general scan show without a public address, wif and hex, only show the total number of scans?

delete line 51
```
    print (total, caddr, key.to_hex(), wifc)#, end='\r')
```
replace it with this
```
    print ('Total Find = ',total, end='\r')
```

**Comment by rouze-d** [comment]
> Is there a way to improve the code? For example, you can add more for the selected range
> 
> **low = 0x100000000000000000 high = 0x1fffffffffffffffff**
> 
> If possible, please improve the project.
> 
> I am very sure that, thanks to your code, I or another person will find a bitcoin puzzle 😀

i use bit module, so can't..
you can use ecloop :
https://github.com/vladkens/ecloop
it works fine in termux

**Comment by turalyf** [comment]
> > Is there a way to improve the code? For example, you can add more for the selected range
> 
> > 
> 
> > **low = 0x100000000000000000 high = 0x1fffffffffffffffff**
> 
> > 
> 
> > If possible, please improve the project.
> 
> > 
> 
> > I am very sure that, thanks to your code, I or another person will find a bitcoin puzzle 😀
> 
> 
> 
> i use bit module, so can't..
> 
> you can use ecloop :
> 
> https://github.com/vladkens/ecloop
> 
> it works fine in termux
> 
> 

Thank you for the information, I'll try.
But the bit module randomly scans very fast, it's a pity that it doesn't support the range

**Comment by rouze-d** [comment]
done. Thanks for waiting ☺️
https://github.com/rouze-d/btc-puzzle/blob/main/puzzle2.py

**Comment by rouze-d** [comment]
> > > Is there a way to improve the code? For example, you can add more for the selected range
> > 
> > 
> > > 
> > 
> > 
> > > **low = 0x100000000000000000 high = 0x1fffffffffffffffff**
> > 
> > 
> > > 
> > 
> > 
> > > If possible, please improve the project.
> > 
> > 
> > > 
> > 
> > 
> > > I am very sure that, thanks to your code, I or another person will find a bitcoin puzzle 😀
> > 
> > 
> > i use bit module, so can't..
> > you can use ecloop :
> > https://github.com/vladkens/ecloop
> > it works fine in termux
> 
> Thank you for the information, I'll try. But the bit module randomly scans very fast, it's a pity that it doesn't support the range

done. Thanks for waiting ☺️
https://github.com/rouze-d/btc-puzzle/blob/main/puzzle2.py

**Comment by turalyf** [comment]
> > > > Is there a way to improve the code? For example, you can add more for the selected range
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > **low = 0x100000000000000000 high = 0x1fffffffffffffffff**
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > If possible, please improve the project.
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > I am very sure that, thanks to your code, I or another person will find a bitcoin puzzle 😀
> 
> > > 
> 
> > > 
> 
> > > i use bit module, so can't..
> 
> > > you can use ecloop :
> 
> > > https://github.com/vladkens/ecloop
> 
> > > it works fine in termux
> 
> > 
> 
> > Thank you for the information, I'll try. But the bit module randomly scans very fast, it's a pity that it doesn't support the range
> 
> 
> 
> done. Thanks for waiting ☺️
> 
> https://github.com/rouze-d/btc-puzzle/blob/main/puzzle2.py


I appreciate your work. thank you for your efforts, I really hope your project will be useful in the field of finding puzzles for all up to 160 bits.
